# Site settings
title: Wir Verkaufen unsere Domain
domain: catering-velbert.de
email: test-email@test.com
telefon: 753497391/6656
description: "Sichern Sie sich jetzt diese Domain für ihr Projekt"
domainInfos: "Infos in die yml datei HIER reinschreiben"
domainProcess: "When you find a domain you like, please express your interest to the seller of the said domain. (alternative When you find a domain you like, please contact the seller of the domain)"
# Color settings (hex-codes without the leading hash-tag)
color:
  navBar: '#1e748f'
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames(Buttons ganz unten auf der Seite) (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
