# Site settings
title: Wir Verkaufen unsere Domain
domain: catering-velbert.de
email: test-email@test.com
telefon: 753497391/6656
url: https://example.github.io
description: "Wir Verkaufen unsere domain "
domainInfos: "Infos in die yml datei HIER reinschreiben"

# Color settings (hex-codes without the leading hash-tag)
color:
  navBar: '#1e748f'
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
